changelog:
  exclude:
    labels:
    - ignore-for-release

  categories:
    - title: 🎉 Exciting New Features
      labels:
      - enhancement

    - title: 🧰 Fixes
      labels:
      - bug

    - title: 🔗 Frontend Dependencies
      labels:
      - dependencies
      - frontend

    - title: 🔗 backend/1-service-registry Dependencies
      labels:
      - dependencies
      - backend/1-service-registry

    - title: 🔗 backend/2-api-gateway Dependencies
      labels:
      - dependencies
      - backend/2-api-gateway

    - title: 🔗 backend/3-auth Dependencies
      labels:
      - dependencies
      - backend/3-auth

    - title: 🔗 backend/4-api-gateway Dependencies
      labels:
      - dependencies
      - backend/4-api-gateway

    - title: 🔗 Other Dependencies
      labels:
      - dependencies

    - title: 🎨 Other Changes
      labels:
      - '*'
      exclude:
        labels:
        - enhancement
        - bug
        - dependencies
