apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: backend-1-service-registry

resources:
- deployment.yaml
- service.yaml

vars:
- name: BACKEND_1_SERVICE_REGISTRY_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: 1-service-registry
