server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: ${HOST:backend-1-service-registry}
  client:
    register-with-eureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 15
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: true

logging:
  level:
    ROOT: WARN
    com.netflix.eureka: WARN
    com.netflix.discovery: ERROR
