apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: worker
        image: socialcomputing/elas-official-backend-5-studycompass
        command: [ worker ]
        env:
        - name: REDIS_HOST
          value: $(BACKEND_5_STUDYCOMPASS_REDIS_SERVICE)
        - name: NEO4J_HOSTNAME
          value: $(BACKEND_5_STUDYCOMPASS_NEO4J_SERVICE)
        - name: NEO4J_PASSWORD
          value: password
