server:
  port: 8000
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: ELAS-E3SELECTOR
          uri: lb://ELAS-E3SELECTOR
          predicates:
            - Path=/api/e3selector/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Okta configuration for api gateway
okta:
  oauth2:
    issuer: https://dev-90486397.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaaqu4nxdodJ06vO5d7
    client-secret: UJfUFnRw2nXVSoHZMabeOieDd1_jDCU4pnaxQdu-74UV_8801PubGAJaM4CSzuz5
    scopes: openid, profile, email, offline_access
